Update README.md
haxxorsid/referralboard pull request #39
Opened 2022-02-04 02:08 UTC by shashank136

Updated the readme file to add links for accessing documentation.

2022-02-04 03:15 UTC, haxxorsid commented
@shashank136 I have moved everything in README to Home page of wiki. You can clear everything in README, except group member names  and add all 4-5 Wiki page links in the README.

Once, we have a Sprint1.md, we should link that as well from README.

2022-02-04 03:20 UTC, shashank136 commented
> @shashank136 I have moved everything in README to Home page of wiki. You can clear everything in README, except group member names and add all 4 Wiki page links (you left out Home page).
> 
> Once, we have a Sprint1.md, we should link that as well from README.

Updated the readme file to direct reader to Wiki pages

2022-02-04 03:21 UTC, haxxorsid commented on README.md
> +### How to raise an bug or feature request?
"How to raise an bug or feature request?" is about creating an issue. Our branching strategy only talks about creating Pull requests and branches. So, you can write "GIT Branching Strategy" instead.

2022-02-04 03:23 UTC, haxxorsid commented on README.md
> +### About the project
Need better heading.

2022-02-04 03:24 UTC, shashank136 commented on README.md
> +### About the project
Suggestions are welcome 😅

2022-02-04 03:25 UTC, haxxorsid commented on README.md
> +### GIT Branching Strategy?
remove question mark

2022-02-04 03:27 UTC, haxxorsid requested changes

2022-02-04 03:27 UTC, haxxorsid commented on README.md
> +### About the project
Wiki or Getting Started or Documentation or Learn More.

2022-02-04 03:28 UTC, haxxorsid commented on README.md
> +### About the project
Wiki or Getting Started or Documentation or Learn More

2022-02-04 03:30 UTC, bahetianjali approved these changes, later dismissed

2022-02-04 03:33 UTC, haxxorsid requested changes

2022-02-04 03:33 UTC, haxxorsid commented on README.md
> +- [Wiki](https://github.com/haxxorsid/referralboard/wiki)
About?

2022-02-04 03:41 UTC, haxxorsid commented on README.md
> +- [About the project?](https://github.com/haxxorsid/referralboard/wiki)
![Drag Racing](https://i.ibb.co/Lxzs5H1/63w8qv.jpg)

2022-02-04 03:46 UTC, haxxorsid requested changes

2022-02-04 03:46 UTC, haxxorsid commented on README.md
> +### Wiki
##Wiki not ###Wiki

2022-02-04 03:51 UTC, haxxorsid approved these changes, later dismissed
Approved

2022-02-04 03:52 UTC, haxxorsid submitted a review, later dismissed

2022-02-04 05:13 UTC, Vineetkhadloya submitted a review, later dismissed
Good.

2022-02-04 16:40 UTC, haxxorsid approved these changes, later dismissed

2022-02-04 16:45 UTC, bahetianjali submitted a review, later dismissed

2022-02-04 16:45 UTC, haxxorsid approved these changes, later dismissed

2022-02-04 23:12 UTC, haxxorsid approved these changes

2022-02-05 00:43 UTC, bahetianjali approved these changes

2022-02-05 01:57 UTC, Vineetkhadloya approved these changes
Good Job !!

2022-02-05 01:58 UTC, merged